name: Build, Publish & QA deploy

on:
  push:
    branches:
      - development


concurrency:
  group: qa-deploy


jobs:

  test:
    uses: slimkrazy/workflow-tests/.github/workflows/test.yaml@development


  generate-image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.gen-tag-name.outputs.tag }}

    steps:
      - name: Generate image tag name
        id: gen-tag-name
        run: |
          echo "tag=`date +%Y%m%d%H%M`" >> $GITHUB_OUTPUT


  build-images:
    needs:
      - test
      - generate-image-tag
    uses: slimkrazy/workflow-tests/.github/workflows/build-images.yaml@development
    with:
      image-tag: ${{ needs.generate-image-tag.outputs.tag }}


  deploy-qa:
    runs-on: ubuntu-latest
    needs:
      - build-images
      - generate-image-tag
    steps:
      - name: Deploy to QA
        run: |
          echo "Shared deployment job, deploying to QA using image tag: ${{ needs.generate-image-tag.outputs.tag }}"


  tag:
    needs:
      - deploy-qa
      - generate-image-tag

    uses: slimkrazy/workflow-tests/.github/workflows/create-tag.yaml@development
    with:
      git-tag: ${{needs.generate-image-tag.outputs.tag}}
