name: Build & Push images

on:
  push:
    branches:
      - development

jobs:

  lint:
    uses: slimkrazy/workflow-tests/.github/workflows/lint.yaml@development

  test:
    uses: slimkrazy/workflow-tests/.github/workflows/test.yaml@development

  deploy-qa:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      run: |
        echo "Shared deployment job"
