name: Build & Push images

on:
  push:
    branches:
      - development

jobs:

  lint:
    uses: slimkrazy/workflow-tests/.github/workflows/lint.yaml@development

  test:
    uses: slimkrazy/workflow-tests/.github/workflows/test.yaml@development

  build-images:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Build all images
        run: |
          echo "Shared deployment job, deploying to QA"

  deploy-qa:
    runs-on: ubuntu-latest
    needs:
      - build-images
    steps:
      - name: Deploy to QA
        run: |
          echo "Shared deployment job, deploying to QA"
