name: Build, Publish & QA deploy

on:
  push:
    branches:
      - development

jobs:

  test:
    uses: slimkrazy/workflow-tests/.github/workflows/test.yaml@development

  build-images:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Build all images
        run: |
          echo "Shared deployment job, deploying to QA"

  deploy-qa:
    runs-on: ubuntu-latest
    needs:
      - build-images
    steps:
      - name: Deploy to QA
        run: |
          echo "Shared deployment job, deploying to QA"

  tag:
    runs-on: ubuntu-latest
    needs:
      - deploy-qa

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: tag changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"
          d=`date +%Y%m%d%H%M`
          git tag -a $d -m "build $d"
          git push origin $d
