name: Lint

on:
  workflow_call:

jobs:

  lint:
    name: Lint the code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run the  Linter
        run: |
          echo "Branch name follows"
          echo "${{github.head_ref}}"
          echo "Run the linter"
