name: Build & publish hotfix

on:
  push:
    branches:
      - master

jobs:

  determine-merged-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.id-determine-merged-branch-name.outputs.branch }}

    steps:
      - name: Determine merged branch name
        id: id-determine-merged-branch-name
        uses: tonynguyenit18/github-action-custom-vars@v1
        run: |
          echo "branch=$RECENT_MERGED_BRANCH_NAME" >> $GITHUB_OUTPUT


  test:
    needs: determine-merged-branch
    if: ${{ startsWith(needs.determine-merged-branch.outputs.branch, 'hotfix/') }}
    uses: slimkrazy/workflow-tests/.github/workflows/test.yaml@development


  generate-image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.gen-tag-name.outputs.tag }}
    steps:
      - name: Generate image tag name
        id: gen-tag-name
        run: |
          echo "tag=`date +%Y%m%d%H%M`-hotfix" >> $GITHUB_OUTPUT


  build-images:
    needs:
      - test
      - generate-image-tag

    uses: slimkrazy/workflow-tests/.github/workflows/build-images.yaml@development
    with:
      image-tag: ${{needs.generate-image-tag.outputs.tag}}

  tag:
    needs:
      - build-images
      - generate-image-tag
    uses: slimkrazy/workflow-tests/.github/workflows/create-tag.yaml@development
    with:
      git-tag: ${{needs.generate-image-tag.outputs.tag}}
