name: Build & publish hotfix

on:
  push:
    branches:
      - master

jobs:

  test:
    if: ${{ startsWith(github.head_ref, 'hotfix/') }}
    uses: slimkrazy/workflow-tests/.github/workflows/test.yaml@development


  generate-image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.gen-tag-name.outputs.tag }}
    steps:
      - name: Generate image tag name
        id: gen-tag-name
        run: |
          echo "tag=`date +%Y%m%d%H%M`-hotfix" >> $GITHUB_OUTPUT


  build-images:
    runs-on: ubuntu-latest
    needs:
      - test
      - generate-image-tag

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build and publish images
        uses: slimkrazy/workflow-tests/.github/workflows/build-images.yaml@development
        with:
          image-tag: ${{steps.generate-image-tag.outputs.tag}}

  tag:
    needs:
      - build-images
    uses: slimkrazy/workflow-tests/.github/workflows/create-tag.yaml@development
