name: master PR lint and test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:

  lint:
    uses: slimkrazy/workflow-tests/.github/workflows/lint.yaml@development

  test:
    uses: slimkrazy/workflow-tests/.github/workflows/test.yaml@development
