name: Build & publish hotfix

on:
  push:
    branches:
      - master

jobs:

  determine-merged-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.id-determine-merged-branch-name.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine merged branch name
        uses: tonynguyenit18/github-action-custom-vars@v1

      - name: Generate output
        id: id-determine-merged-branch-name
        run: |
          echo "branch=$RECENT_MERGED_BRANCH_NAME" >> $GITHUB_OUTPUT


  test:
    needs: determine-merged-branch
    if: ${{ startsWith(needs.determine-merged-branch.outputs.branch, 'hotfix/') }}
    uses: slimkrazy/workflow-tests/.github/workflows/test.yaml@development


  generate-hotfix-image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.gen-tag-name.outputs.tag }}
    steps:
      - name: Generate image tag name
        id: gen-tag-name
        run: |
          echo "tag=`date +%Y%m%d%H%M`-hotfix" >> $GITHUB_OUTPUT


  build-images:
    needs:
      - test
      - generate-hotfix-image-tag

    uses: slimkrazy/workflow-tests/.github/workflows/build-images.yaml@development
    with:
      image-tag: ${{ needs.generate-hotfix-image-tag.outputs.tag }}


  tag:
    needs:
      - build-images
      - generate-hotfix-image-tag
    uses: slimkrazy/workflow-tests/.github/workflows/create-tag.yaml@development
    with:
      git-tag: ${{ needs.generate-hotfix-image-tag.outputs.tag }}


  open-pull-request:
    runs-on: ubuntu-latest
    needs:
      - tag
      - generate-hotfix-image-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Modify files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"
          git fetch origin master
          git merge origin/master

      - name: Open Hotfix PR to development branch
        uses: peter-evans/create-pull-request@v4
        with:
          base: development
          branch: chore/auto-merge
          title: Merge hotfix ${{ needs.generate-hotfix-image-tag.outputs.tag }}
          body: Automated changes triggered by hotfix build ${{ needs.generate-hotfix-image-tag.outputs.tag }} [skip-ci]
          delete-branch: true
