name: Merge validator

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
      - development

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Validate branch name and target branch combination
      if: (github.ref_name == 'master' && (!startsWith(github.head_ref, 'hotfix/') &&  github.head_ref == 'development'))
      run: |
        echo "Invalid branch merge attempt"
        exit 1
