name: Merge validator

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
      - development

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:

    - name: Validate master branch merge attempt
      if: ${{ github.base_ref == 'master' && (!startsWith(github.head_ref, 'hotfix/') || github.head_ref != 'development')}}
      run: |
        echo "Invalid branch merge attempt. Only development and hotfixes permitted to be merged to master"
        exit 1

    - name: Validate development branch merge attempt
      if: ${{ github.base_ref == 'development' && !startsWith(github.head_ref, 'feature/') && !startsWith(github.head_ref, 'chore/') && !startsWith(github.head_ref, 'fix/') }}
      run: |
        echo "Invalid branch merge attempt."
        exit 1
