name: Production release

on:
  release:
    types: [created]

jobs:

  update-eu-central-1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref_name }}

    - name: update-eu-central-1
      run: |
        echo "Updating eu-central-1"

  merge-to-master:
    runs-on: ubuntu-latest
    needs:
      - update-eu-central-1
    steps:
    - name: checkout-master
      uses: actions/checkout@v2
      with:
        ref: master

    - name: git-merge
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions"
        git fetch origin refs/tags/${{ github.ref_name }}
        git merge --no-commit --no-ff ${{ github.ref_name }}
        git push origin master


