name: Production release

on:
  release:
    types: [created]

jobs:

  update-eu-central-1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    - name: update-eu-central-1
      run: |
        echo "Updating eu-central-1 with version: ${{ github.ref_name }}"


  merge-feature-tag-to-master:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref_name , 'hotfix') }}

    needs:
      - update-eu-central-1

    steps:
    - name: checkout-master
      uses: actions/checkout@v3
      with:
        ref: master

    - name: git-merge
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions"
        git fetch --tags
        git status
        git merge ${{ github.ref_name }}
        git push origin master
