name: Test

on: [workflow_call]

jobs:

  test:
    name: Run the tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run the tests
        run: echo "Run the tests"
